### ISSUE TITLE
(crash): DirectBootMigration crash due to background service restriction

### ISSUE THREAD

**Issue by TogoFire** [Chaitanyakm/vendor_bcr#2]
Rom: VoltageOS 4.0 A15.
Device: Oneplus9

Log:
https://bin.cyberknight777.dev/ovmP/raw

type: crash
osVersion: OnePlus/OnePlus9/OnePlus9:14/UKQ1.230924.001/R.1a46f9a_1-1:user/release-keys
package: com.chiller3.bcr:84224
process: com.chiller3.bcr
processUptime: 77 + 45 ms

java.lang.RuntimeException: Unable to start receiver com.chiller3.bcr.DirectBootMigrationReceiver: android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent { cmp=com.chiller3.bcr/.DirectBootMigrationService }: app is in background uid UidRecord{428a860 u0a200 RCVR bg:+67ms idle change:uncachedprocstate procs:0 seq(13521,13520)} caps=-------
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4792)
	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8732)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:585)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
Caused by: android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent { cmp=com.chiller3.bcr/.DirectBootMigrationService }: app is in background uid UidRecord{428a860 u0a200 RCVR bg:+67ms idle change:uncachedprocstate procs:0 seq(13521,13520)} caps=-------
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:2005)
	at android.app.ContextImpl.startService(ContextImpl.java:1960)
	at android.content.ContextWrapper.startService(ContextWrapper.java:827)
	at android.content.ContextWrapper.startService(ContextWrapper.java:827)
	at com.chiller3.bcr.DirectBootMigrationReceiver.onReceive(Unknown Source:29)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4783)
	... 9 more

**Comment by TogoFire** [comment]
Nvm.
I reported in the wrong place.
